// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cze'
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	logg: {
		/**
		 * b​r​i​ ​i​s​h
		 */
		title: string
	}
}

export type TranslationFunctions = {
	logg: {
		/**
		 * bri ish
		 */
		title: () => LocalizedString
	}
}

export type Formatters = {}
