// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cze'
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​h​i​s​ ​l​o​g​ ​w​a​s​ ​c​a​l​l​e​d​ ​f​r​o​m​ ​'​{​f​i​l​e​N​a​m​e​}​'
	 * @param {string} fileName
	 */
	log: RequiredParams<'fileName'>
	logg: {
		/**
		 * b​r​i​ ​i​s​h
		 */
		title: string
	}
	/**
	 * /​b​l​o​g​,​ ​/​b​a​n​a​n​a​,​ ​/​o​m​g​/​u​w​u
	 */
	firstParam: string
}

export type TranslationFunctions = {
	/**
	 * This log was called from '{fileName}'
	 */
	log: (arg: { fileName: string }) => LocalizedString
	logg: {
		/**
		 * bri ish
		 */
		title: () => LocalizedString
	}
	/**
	 * /blog, /banana, /omg/uwu
	 */
	firstParam: () => LocalizedString
}

export type Formatters = {}
